# Generated by Django 4.1.4 on 2022-12-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[
                ('admin', 'Админ'), ('user', 'Пользователь'),
                ('moderator', 'Модератор')],
                default='user', max_length=20, verbose_name='статус'),
        ),
    ]
