# Generated by Django 2.2.16 on 2023-02-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230207_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'Модератор'), ('admin', 'Админ'), ('user', 'Пользователь')], default='user', max_length=20, verbose_name='статус'),
        ),
    ]
